"""
 Encrypted Results Visualizer
Visualize comprehensive data analysis WITHOUT accessing raw CSV data
Uses statistical summaries generated by process_data.py
"""

import sys
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
from datetime import datetime
from typing import Dict, List

# Setup
project_root = Path(__file__).parent
results_dir = project_root / 'results'

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (15, 10)
plt.rcParams['font.size'] = 10


class EncryptedDataAnalyzer:
    """Analyze and visualize encrypted computation results without raw data access."""
    
    def __init__(self):
        """Initialize analyzer."""
        self.results_dir = results_dir
        self.results_dir.mkdir(exist_ok=True)
        self.results = {}
        
    def load_results(self, result_files: List[str] = None):
        """Load analysis results from JSON files."""
        if result_files is None:
            result_files = [
                'encrypted_data_results.json',
                'statistical_summary.json',
                'range_analysis.json',
                'encrypted_statistics.json',
                'fl_simulation_results.json'
            ]
        
        print("="*70)
        print("ENCRYPTED DATA ANALYSIS & VISUALIZATION")
        print("="*70)
        print(f"\n📊 Loading encrypted analysis results...")
        
        loaded_count = 0
        for filename in result_files:
            filepath = self.results_dir / filename
            if filepath.exists():
                with open(filepath, 'r') as f:
                    key = filename.replace('.json', '')
                    self.results[key] = json.load(f)
                print(f"  ✓ {filename}")
                loaded_count += 1
            else:
                print(f"  ⚠️  {filename} not found (skipping)")
        
        if loaded_count == 0:
            print("\n❌ ERROR: No result files found!")
            print(f"   Please run 'process_data.py' first to generate results.")
            print(f"   Expected location: {self.results_dir.absolute()}")
            sys.exit(1)
        
        print(f"\n✓ Loaded {loaded_count} result file(s)")
        return self.results
    
    def plot_data_distribution(self):
        """Visualize data distribution from encrypted statistical summary."""
        if 'statistical_summary' not in self.results:
            print("⚠️  Statistical summary not available. Skipping distribution plot.")
            return
        
        stats = self.results['statistical_summary']
        
        fig, axes = plt.subplots(2, 2, figsize=(16, 12))
        fig.suptitle(f"Data Distribution Analysis: {stats['column_name']}\n(From Encrypted Computations)", 
                     fontsize=16, fontweight='bold')
        
        # Plot 1: Histogram from encrypted data
        ax1 = axes[0, 0]
        if 'histogram' in stats:
            hist_data = stats['histogram']
            bin_centers = hist_data['bin_centers']
            counts = hist_data['counts']
            
            ax1.bar(bin_centers, counts, width=(bin_centers[1]-bin_centers[0])*0.9,
                   color='steelblue', edgecolor='black', alpha=0.7)
            ax1.axvline(stats['mean'], color='red', linestyle='--', linewidth=2, 
                       label=f"Mean: {stats['mean']:.2f}")
            ax1.axvline(stats['median'], color='green', linestyle='--', linewidth=2,
                       label=f"Median: {stats['median']:.2f}")
            ax1.set_xlabel(stats['column_name'])
            ax1.set_ylabel('Frequency')
            ax1.set_title('Distribution (From Encrypted Data)')
            ax1.legend()
            ax1.grid(True, alpha=0.3)
        
        # Plot 2: Box Plot representation
        ax2 = axes[0, 1]
        box_data = {
            'min': stats['min'],
            'q1': stats['q1'],
            'median': stats['median'],
            'q3': stats['q3'],
            'max': stats['max']
        }
        
        # Manual box plot
        bp = ax2.boxplot([[box_data['min'], box_data['q1'], box_data['median'], 
                          box_data['q3'], box_data['max']]], 
                         vert=True, patch_artist=True, widths=0.5)
        bp['boxes'][0].set_facecolor('lightblue')
        bp['boxes'][0].set_edgecolor('black')
        
        ax2.set_ylabel(stats['column_name'])
        ax2.set_title('Box Plot Summary')
        ax2.grid(True, alpha=0.3, axis='y')
        ax2.set_xticklabels([''])
        
        # Add statistics annotation
        stats_text = (
            f"Min:    {stats['min']:.2f}\n"
            f"Q1:     {stats['q1']:.2f}\n"
            f"Median: {stats['median']:.2f}\n"
            f"Q3:     {stats['q3']:.2f}\n"
            f"Max:    {stats['max']:.2f}\n"
            f"IQR:    {stats['iqr']:.2f}"
        )
        ax2.text(1.3, 0.5, stats_text, transform=ax2.transAxes,
                fontsize=10, verticalalignment='center',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.7))
        
        # Plot 3: Cumulative Distribution (approximated)
        ax3 = axes[1, 0]
        if 'histogram' in stats:
            hist_data = stats['histogram']
            counts = np.array(hist_data['counts'])
            bin_centers = hist_data['bin_centers']
            
            cumulative = np.cumsum(counts) / np.sum(counts) * 100
            ax3.plot(bin_centers, cumulative, linewidth=2, color='purple', marker='o')
            ax3.axhline(50, color='red', linestyle='--', alpha=0.5, label='50th percentile')
            ax3.axhline(75, color='orange', linestyle='--', alpha=0.5, label='75th percentile')
            ax3.set_xlabel(stats['column_name'])
            ax3.set_ylabel('Cumulative Percentage (%)')
            ax3.set_title('Cumulative Distribution Function')
            ax3.legend()
            ax3.grid(True, alpha=0.3)
        
        # Plot 4: Statistics Table
        ax4 = axes[1, 1]
        ax4.axis('off')
        
        table_data = [
            ['Statistic', 'Value'],
            ['Count', f"{stats['count']:,}"],
            ['Mean', f"{stats['mean']:.2f}"],
            ['Median', f"{stats['median']:.2f}"],
            ['Std Dev', f"{stats['std_dev']:.2f}"],
            ['Min', f"{stats['min']:.2f}"],
            ['Max', f"{stats['max']:.2f}"],
            ['Range', f"{stats['range']:.2f}"],
            ['Skewness', f"{stats['skewness']:.3f}"],
            ['Kurtosis', f"{stats['kurtosis']:.3f}"]
        ]
        
        table = ax4.table(cellText=table_data, cellLoc='left', loc='center',
                         colWidths=[0.4, 0.6])
        table.auto_set_font_size(False)
        table.set_fontsize(11)
        table.scale(1, 2)
        
        # Style header
        for i in range(2):
            table[(0, i)].set_facecolor('#4472C4')
            table[(0, i)].set_text_props(weight='bold', color='white')
        
        # Alternate rows
        for i in range(1, len(table_data)):
            for j in range(2):
                if i % 2 == 0:
                    table[(i, j)].set_facecolor('#E7E6E6')
        
        ax4.set_title('Summary Statistics\n(Computed on Encrypted Data)', 
                     fontsize=12, fontweight='bold', pad=20)
        
        plt.tight_layout()
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'encrypted_data_distribution_{timestamp}.png'
        filepath = self.results_dir / filename
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f"\n💾 Saved: {filepath}")
        plt.show()
    
    def plot_range_analysis(self):
        """Visualize range-based analysis."""
        if 'range_analysis' not in self.results:
            print("⚠️  Range analysis not available. Skipping range plot.")
            return
        
        range_data = self.results['range_analysis']
        
        fig, axes = plt.subplots(1, 2, figsize=(16, 6))
        fig.suptitle(f"Range Analysis: {range_data['column_name']}\n(From Encrypted Computations)",
                     fontsize=16, fontweight='bold')
        
        # Plot 1: Count distribution by range
        ax1 = axes[0]
        ranges = range_data['ranges']
        
        range_names = list(ranges.keys())
        counts = [ranges[r]['count'] for r in range_names]
        percentages = [ranges[r]['percentage'] for r in range_names]
        colors = ['#3498db', '#2ecc71', '#e74c3c']
        
        bars = ax1.bar(range_names, counts, color=colors, edgecolor='black', alpha=0.8)
        ax1.set_ylabel('Count')
        ax1.set_xlabel('Salary Range')
        ax1.set_title('Sample Distribution by Range')
        ax1.grid(True, axis='y', alpha=0.3)
        
        # Add value labels
        for bar, count, pct in zip(bars, counts, percentages):
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{count:,}\n({pct:.1f}%)',
                    ha='center', va='bottom', fontsize=10, fontweight='bold')
        
        # Plot 2: Mean comparison by range
        ax2 = axes[1]
        means = [ranges[r]['mean'] for r in range_names]
        
        bars = ax2.bar(range_names, means, color=colors, edgecolor='black', alpha=0.8)
        ax2.set_ylabel('Mean Value')
        ax2.set_xlabel('Salary Range')
        ax2.set_title('Average by Range (Encrypted Computation)')
        ax2.grid(True, axis='y', alpha=0.3)
        
        # Add value labels and range bounds
        for bar, mean, range_name in zip(bars, means, range_names):
            height = bar.get_height()
            bounds = ranges[range_name]['range_bounds']
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                    f'{mean:.2f}\n[{bounds[0]:.0f}-{bounds[1]:.0f}]',
                    ha='center', va='bottom', fontsize=9)
        
        plt.tight_layout()
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'encrypted_range_analysis_{timestamp}.png'
        filepath = self.results_dir / filename
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f"💾 Saved: {filepath}")
        plt.show()
    
    def plot_fl_client_analysis(self):
        """Visualize federated learning client-level analysis."""
        if 'fl_simulation_results' not in self.results:
            print("⚠️  FL results not available. Skipping FL client plot.")
            return
        
        fl_data = self.results['fl_simulation_results']
        
        if 'client_statistics' not in fl_data:
            print("⚠️  Client statistics not available.")
            return
        
        client_stats = fl_data['client_statistics']
        
        fig, axes = plt.subplots(1, 3, figsize=(18, 5))
        fig.suptitle('Federated Learning Client Analysis\n(Privacy-Preserving)', 
                     fontsize=16, fontweight='bold')
        
        # Extract data
        client_ids = [c['client_id'] for c in client_stats]
        sample_counts = [c['sample_count'] for c in client_stats]
        local_means = [c['local_mean'] for c in client_stats]
        comp_times = [c['computation_time'] for c in client_stats]
        
        # Plot 1: Sample distribution
        ax1 = axes[0]
        colors = plt.cm.viridis(np.linspace(0.3, 0.9, len(client_ids)))
        bars = ax1.bar([f'C{cid}' for cid in client_ids], sample_counts, 
                      color=colors, edgecolor='black', alpha=0.8)
        ax1.set_ylabel('Sample Count')
        ax1.set_xlabel('Client')
        ax1.set_title('Data Distribution Across Clients')
        ax1.grid(True, axis='y', alpha=0.3)
        
        for bar in bars:
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{int(height):,}', ha='center', va='bottom')
        
        # Plot 2: Local means
        ax2 = axes[1]
        bars = ax2.bar([f'C{cid}' for cid in client_ids], local_means,
                      color='#3498db', edgecolor='black', alpha=0.8)
        ax2.set_ylabel('Local Mean')
        ax2.set_xlabel('Client')
        ax2.set_title('Local Statistics per Client')
        ax2.grid(True, axis='y', alpha=0.3)
        
        # Add global mean line
        global_mean = fl_data.get('fl_average', np.mean(local_means))
        ax2.axhline(global_mean, color='red', linestyle='--', linewidth=2,
                   label=f'Global Mean: {global_mean:.2f}')
        ax2.legend()
        
        for bar in bars:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.2f}', ha='center', va='bottom')
        
        # Plot 3: Computation times
        ax3 = axes[2]
        bars = ax3.bar([f'C{cid}' for cid in client_ids], comp_times,
                      color='#2ecc71', edgecolor='black', alpha=0.8)
        ax3.set_ylabel('Time (seconds)')
        ax3.set_xlabel('Client')
        ax3.set_title('Client Computation Time')
        ax3.grid(True, axis='y', alpha=0.3)
        
        for bar in bars:
            height = bar.get_height()
            ax3.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.3f}s', ha='center', va='bottom')
        
        plt.tight_layout()
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'encrypted_fl_clients_{timestamp}.png'
        filepath = self.results_dir / filename
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f"💾 Saved: {filepath}")
        plt.show()
    
    def plot_performance_dashboard(self):
        """Create comprehensive performance dashboard."""
        fig = plt.figure(figsize=(18, 12))
        gs = fig.add_gridspec(3, 3, hspace=0.3, wspace=0.3)
        
        fig.suptitle('Encrypted Data Analysis Dashboard\n🔒 No Raw CSV Data Accessed',
                     fontsize=18, fontweight='bold')
        
        # Plot 1: FL Time Breakdown (large, top-left)
        ax1 = fig.add_subplot(gs[0:2, 0:2])
        if 'fl_simulation_results' in self.results:
            fl = self.results['fl_simulation_results']
            client_times = fl.get('client_computation_times', [])
            agg_time = fl.get('aggregation_time', 0)
            dec_time = fl.get('decryption_time', 0)
            
            labels = ['Client\nComputation', 'Server\nAggregation', 'Decryption']
            sizes = [sum(client_times), agg_time, dec_time]
            colors = ['#3498db', '#2ecc71', '#e74c3c']
            explode = (0.05, 0, 0)
            
            wedges, texts, autotexts = ax1.pie(sizes, labels=labels, autopct='%1.1f%%',
                                                colors=colors, explode=explode, startangle=90,
                                                textprops={'fontsize': 12, 'fontweight': 'bold'})
            ax1.set_title('FL Pipeline Time Distribution', fontsize=14, fontweight='bold', pad=20)
        
        # Plot 2: Key Statistics (top-right)
        ax2 = fig.add_subplot(gs[0, 2])
        ax2.axis('off')
        
        stats_data = [['Metric', 'Value']]
        
        if 'statistical_summary' in self.results:
            stats = self.results['statistical_summary']
            stats_data.extend([
                ['Count', f"{stats['count']:,}"],
                ['Mean', f"{stats['mean']:.2f}"],
                ['Median', f"{stats['median']:.2f}"],
                ['Std Dev', f"{stats['std_dev']:.2f}"],
                ['Min', f"{stats['min']:.2f}"],
                ['Max', f"{stats['max']:.2f}"]
            ])
        
        table = ax2.table(cellText=stats_data, cellLoc='left', loc='center',
                         colWidths=[0.5, 0.5])
        table.auto_set_font_size(False)
        table.set_fontsize(10)
        table.scale(1, 1.8)
        
        for i in range(2):
            table[(0, i)].set_facecolor('#4472C4')
            table[(0, i)].set_text_props(weight='bold', color='white')
        
        for i in range(1, len(stats_data)):
            for j in range(2):
                if i % 2 == 0:
                    table[(i, j)].set_facecolor('#E7E6E6')
        
        ax2.set_title('Summary Statistics', fontsize=12, fontweight='bold', pad=10)
        
        # Plot 3: Histogram (middle-right)
        ax3 = fig.add_subplot(gs[1, 2])
        if 'statistical_summary' in self.results:
            stats = self.results['statistical_summary']
            if 'histogram' in stats:
                hist_data = stats['histogram']
                ax3.bar(hist_data['bin_centers'], hist_data['counts'],
                       width=(hist_data['bin_centers'][1]-hist_data['bin_centers'][0])*0.9,
                       color='steelblue', edgecolor='black', alpha=0.7)
                ax3.set_xlabel('Value', fontsize=9)
                ax3.set_ylabel('Frequency', fontsize=9)
                ax3.set_title('Distribution', fontsize=11, fontweight='bold')
                ax3.tick_params(labelsize=8)
                ax3.grid(True, alpha=0.3)
        
        # Plot 4: Range Analysis (bottom-left)
        ax4 = fig.add_subplot(gs[2, 0])
        if 'range_analysis' in self.results:
            ranges = self.results['range_analysis']['ranges']
            range_names = list(ranges.keys())
            counts = [ranges[r]['count'] for r in range_names]
            colors_range = ['#3498db', '#2ecc71', '#e74c3c']
            
            ax4.bar(range_names, counts, color=colors_range, edgecolor='black', alpha=0.8)
            ax4.set_ylabel('Count', fontsize=10)
            ax4.set_title('Range Distribution', fontsize=11, fontweight='bold')
            ax4.grid(True, axis='y', alpha=0.3)
            ax4.tick_params(labelsize=9)
        
        # Plot 5: FL Accuracy (bottom-middle)
        ax5 = fig.add_subplot(gs[2, 1])
        if 'fl_simulation_results' in self.results:
            fl = self.results['fl_simulation_results']
            true_avg = fl.get('true_average', 0)
            fl_avg = fl.get('fl_average', 0)
            
            x = ['True', 'FL']
            values = [true_avg, fl_avg]
            colors_acc = ['#2ecc71', '#3498db']
            
            bars = ax5.bar(x, values, color=colors_acc, edgecolor='black', alpha=0.8)
            ax5.set_ylabel('Average', fontsize=10)
            ax5.set_title('FL Accuracy', fontsize=11, fontweight='bold')
            ax5.grid(True, axis='y', alpha=0.3)
            
            error = abs(true_avg - fl_avg)
            ax5.text(0.5, 0.95, f'Error: {error:.2e}',
                    transform=ax5.transAxes, ha='center', va='top',
                    bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7),
                    fontsize=9)
        
        # Plot 6: Client Distribution (bottom-right)
        ax6 = fig.add_subplot(gs[2, 2])
        if 'fl_simulation_results' in self.results:
            fl = self.results['fl_simulation_results']
            if 'data_distribution' in fl:
                clients = [f'C{i+1}' for i in range(len(fl['data_distribution']))]
                sizes = fl['data_distribution']
                colors_client = plt.cm.viridis(np.linspace(0.3, 0.9, len(clients)))
                
                ax6.bar(clients, sizes, color=colors_client, edgecolor='black', alpha=0.8)
                ax6.set_ylabel('Samples', fontsize=10)
                ax6.set_title('Client Data Split', fontsize=11, fontweight='bold')
                ax6.grid(True, axis='y', alpha=0.3)
                ax6.tick_params(labelsize=9)
        
        plt.tight_layout()
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'encrypted_analysis_dashboard_{timestamp}.png'
        filepath = self.results_dir / filename
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f"💾 Saved: {filepath}")
        plt.show()
    
    def generate_all_visualizations(self):
        """Generate all visualizations from encrypted results."""
        print("\n📊 Generating visualizations from encrypted results...\n")
        
        print("1. Data Distribution Analysis...")
        self.plot_data_distribution()
        
        print("\n2. Range Analysis...")
        self.plot_range_analysis()
        
        print("\n3. FL Client Analysis...")
        self.plot_fl_client_analysis()
        
        print("\n4. Performance Dashboard...")
        self.plot_performance_dashboard()
        
        print("\n" + "="*70)
        print("✓ ALL VISUALIZATIONS COMPLETE!")
        print("="*70)
        print(f"\nAll plots saved in: {self.results_dir.absolute()}/")
        print("\n🔒 Privacy Guarantee: No raw CSV data was accessed.")
        print("   All visualizations use only encrypted computation results.")


def main():
    """Main visualization function."""
    analyzer = EncryptedDataAnalyzer()
    analyzer.load_results()
    analyzer.generate_all_visualizations()


if __name__ == "__main__":
    main()